FROM node:latest as builder

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

FROM node:slim  as final

WORKDIR /app

COPY --from=builder /app .

EXPOSE 5012
EXPOSE 8000
EXPOSE 8001

CMD npm run prod